# Generated by Django 2.2.4 on 2019-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
